### ISSUE TITLE
AI Confidence buttons inactive.

### ISSUE THREAD

**Issue by angad305** [calebolson123/BabySleepCoach#22]
Both the buttons for AI Confidence are disabled? Please see attached pic.
<img width="347" alt="Screenshot 2023-09-28 192408" src="https://github.com/calebolson123/BabySleepCoach/assets/34420642/eeb38238-6db2-4523-8cce-de24404e5413">

Is there some logic which is preventing them.

**Comment by calebolson123** [comment]
Ah, so I didn't dive into how the cascading rule-logic works in the video. The system has a few levels of rules which are more or less confident and accurate at detecting a sleeping baby. If a more accurate rule is "confident", the system ignores the less accurate rules (e.g. the custom AI model that is trained when you click "Yes" or "No"). In this case, [a more accurate detector](https://developers.google.com/mediapipe/solutions/vision/pose_landmarker) is running, and the system isn't invoking the custom model.

So what's happening is: because it's detecting anatomical features: it's disabling the buttons. I can add to my TODO list to explore enable training even if the custom model is not running.

What's more concerning from your pic is that the overlayed circles where it thinks the face is, seems off. Does it always say, "Anatomical features detected, ignoring custom presence detection AI", even when your baby is out of frame? I may need to increase the confidence threshold of that "rule", so it is less likely to misfire.

**Comment by calebolson123** [comment]
Also, I'm not seeing an arrow in the "sleepometer", pointing to the system's confidence that your baby is sleeping. Do you ever see the arrow?

e.g.
<img width="204" alt="Screenshot 2023-09-28 at 9 59 15 AM" src="https://github.com/calebolson123/BabySleepCoach/assets/21248639/f40db97b-25c1-41d4-a882-c695f3915924">

**Comment by angad305** [comment]
> Ah, so I didn't dive into how the cascading rule-logic works in the video. The system has a few levels of rules which are more or less confident and accurate at detecting a sleeping baby. If a more accurate rule is "confident", the system ignores the less accurate rules (e.g. the custom AI model that is trained when you click "Yes" or "No"). In this case, [a more accurate detector](https://developers.google.com/mediapipe/solutions/vision/pose_landmarker) is running, and the system isn't invoking the custom model.
> 
> So what's happening is: because it's detecting anatomical features: it's disabling the buttons. I can add to my TODO list to explore enable training even if the custom model is not running.
> 
> What's more concerning from your pic is that the overlayed circles where it thinks the face is, seems off. Does it always say, "Anatomical features detected, ignoring custom presence detection AI", even when your baby is out of frame? I may need to increase the confidence threshold of that "rule", so it is less likely to misfire.

i do get Understood the logic part. thank you for the explanation. 
See below screenshot, the "Anatomical features detected, ignoring custom presence detection AI" is always there mostly.
![WhatsApp Image 2023-09-28 at 23 48 02](https://github.com/calebolson123/BabySleepCoach/assets/34420642/0266f931-847e-4528-b427-c19b2d9c0b71)

**Comment by angad305** [comment]
> Also, I'm not seeing an arrow in the "sleepometer", pointing to the system's confidence that your baby is sleeping. Do you ever see the arrow?
> 
> e.g. <img alt="Screenshot 2023-09-28 at 9 59 15 AM" width="204" src="https://user-images.githubusercontent.com/21248639/271327894-f40db97b-25c1-41d4-a882-c695f3915924.png">

the issue is on the big screen monitor when i use chrome, on mobile phone the arrow pointer is working fine.

**Comment by calebolson123** [comment]
Got it on the mobile vs desktop.. I didn't spend time making the web app portion responsive. Primary use case is mobile.

Regarding always seeing, "Anatomical features detected...", can you try going into `main.py` and increasing the two confidence arg values?

[Here](https://github.com/calebolson123/BabySleepCoach/blob/e44c49377d994ef7fe711440f4b837c1e6cffd4d/main.py#L111)

For my crib environment, I found a lower value (looks like 0.3) worked well for me and my baby. But you may need to increase this value so that you aren't getting false-positives, if that makes sense. If it's triggering the MediaPipe pose-detection model, then it won't default to the new final catch-all model.

This reminds me, I should expose an easier way within the web app to enable users to more easily fine-tune these thresholds
